import os
import logging
import time

def create_markdown(title, podcast_name, summary, major_points, quotes, sources, transcript, file_path):
    """
    Creates a Markdown file (.md) with the analyzed content of the podcast episode.

    Args:
        title (str): The title of the episode.
        podcast_name (str): The name of the podcast.
        summary (str): The summary generated by the LLM.
        major_points (list): A list of major points from the LLM.
        quotes (list): A list of important quotes from the LLM.
        sources (list): A list of sources referenced, from the LLM.
        transcript (str): The full transcript of the episode.
        file_path (str): The full path where the Markdown file should be saved.
    """
    try:
        current_date = time.strftime("%Y-%m-%d")
        lines = []
        
        # Title and Header Information
        lines.append(f"# {title}")
        lines.append(f"**Podcast:** {podcast_name}")
        lines.append(f"**Date Processed:** {current_date}")
        lines.append("")
        
        # Summary Section
        lines.append("## Summary")
        lines.append(summary)
        lines.append("")
        
        # Major Takeaways
        lines.append("## Major Takeaways")
        if major_points:
            for point in major_points:
                lines.append(f"- {point}")
        else:
            lines.append("No major points were identified.")
        lines.append("")
        
        # Notable Quotes
        lines.append("## Notable Quotes")
        if quotes:
            for quote in quotes:
                lines.append(f"> {quote}")
                lines.append("")
        else:
            lines.append("No notable quotes were identified.")
            lines.append("")
            
        # Sources Referenced
        lines.append("## Sources Referenced")
        if sources:
            for source in sources:
                lines.append(f"- {source}")
        else:
            lines.append("No sources were referenced.")
        lines.append("")
        
        # Full Transcript
        lines.append("## Full Transcript")
        lines.append(transcript)
        lines.append("")
        
        md_content = "\n".join(lines)
        
        # Ensure parent directory of file_path exists
        dir_name = os.path.dirname(file_path)
        if dir_name and not os.path.exists(dir_name):
            os.makedirs(dir_name, exist_ok=True)
            
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
            
        logging.info(f"Markdown file successfully created: {file_path}")
        return True
        
    except Exception as e:
        logging.error(f"An error occurred during Markdown generation: {e}", exc_info=True)
        return False
